name: CI Pipeline

on:
  push:
    branches: [ "admin" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build the Docker image
      run: docker build -t $DOCKER_USERNAME/librario_back:latest .

    - name: Push to Docker Hub
      run: docker push $DOCKER_USERNAME/librario_back:latest
