name: CI/CD Pipeline

on:
  push:
    branches: ['admin']  # Trigger on push to the 'admin' branch
  pull_request:
    branches: ['main']  # Optionally, for pull requests to 'main'

env:
  BACKEND_DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/Librario_back
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/admin'  # Trigger on push to 'admin' branch

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./Librario_back
          file: ./Librario_back/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_DOCKER_IMAGE }}:latest
            ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.sha }}
          build-args: |
            NODE_ENV=production
          no-cache: true
